jobs:

  - job: TestBuildPublish
    pool:
      vmImage: ubuntu-latest

    steps:
    - task: Gradle@2
      displayName: 'gradlew publishToMavenLocal'
      inputs:
        gradleWrapperFile: 'gradlew'
        tasks: 'publishTestFluentUIPublicationToMavenLocal'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '$(jdkVersion)'
        options: '-PtestGroupId=$(testGroupId)'
