jobs:

  - job: Build
    pool:
      vmImage: 'macos-latest'

    steps:
    - task: Gradle@2
      displayName: 'gradlew build testPublish'
      inputs:
        gradleWrapperFile: 'gradlew'
        tasks: 'build'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '$(jdkVersion)'
        options: '-PappCenterSecret=$(appCenterSecret) -PsigningKeyPassword=$(signingKeyPassword) -PsigningKeyStorePassword=$(signingKeyStorePassword) -POSSRHUsername=$(ossrhUsername) -POSSRHPassword=$(ossrhPassword) -PtestGroupId=$(testGroupId)'
