jobs:

  - job: TestBuildPublish
    pool:
      vmImage: ubuntu-latest

    steps:
    - task: Gradle@2
      displayName: 'gradlew build publishTestFluentUIPublicationToMavenLocal'
      inputs:
        gradleWrapperFile: 'gradlew'
        tasks: 'build publishToMavenLocal'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '$(jdkVersion)'
        options: '-PappCenterSecret=$(appCenterSecret) -PsigningKeyPassword=$(signingKeyPassword) -PsigningKeyStorePassword=$(signingKeyStorePassword) -POSSRHUsername=$(ossrhUsername) -POSSRHPassword=$(ossrhPassword) -PtestGroupId=$(testGroupId)'
